import { mkdirSync, writeFileSync } from 'node:fs'

const pages = {
  ko: {
    about: ['서비스 소개·문의', '누크야! 소개', `
      <p class="lead">누크야!는 한국 프로야구 선수의 정보를 비교하며 정답을 찾는 무료 퀴즈 게임입니다. 선수 이름을 많이 아는 것뿐 아니라, 매 추측에서 얻은 단서를 조합하는 즐거움을 목표로 합니다.</p><h2>어떤 게임인가요?</h2><p>최대 9번의 추측으로 숨겨진 선수를 찾습니다. 구단과 포지션 같은 범주형 정보, 등번호·출생연도·키·몸무게 같은 숫자 정보가 서로 다른 단서가 됩니다. 좋아하는 한 구단부터 시작하거나 여러 구단을 함께 선택할 수 있습니다. 한국어와 영어 화면을 제공합니다.</p><h2>명단과 정보의 한계</h2><p>게임 안의 명단 기준일을 기준으로 플레이해주세요. 실제 선수 등록 현황은 계속 변하며 이적, 등록·말소, 프로필 수정 사항이 즉시 반영되지 않을 수 있습니다. 정확한 최신 등록 정보가 필요한 경우 <a href="https://www.koreabaseball.com/">KBO 공식 홈페이지</a>를 함께 확인하세요. 누크야!의 게임 결과는 공식 선수 기록의 증명이 아닙니다.</p><h2>광고와 외부 링크</h2><p>서비스에는 외부 서비스의 홍보 배너가 표시될 수 있습니다. 배너에는 광고임을 표시하며, 클릭하면 별도 사이트로 이동합니다. Google 광고를 사용하는 경우에도 게임 준비·오류 화면과 안내 페이지에서는 요청하지 않도록 구성합니다. 외부 사이트의 서비스와 개인정보 처리 방식은 해당 사이트에서 확인해주세요.</p><h2>문의 및 오류 제보</h2><p><a class="button" href="mailto:fortelior@tendom.co.kr">fortelior@tendom.co.kr</a></p><p>선수 정보 정정, 게임 오류, 서비스 및 개인정보 문의를 받습니다. 오류 제보에는 발생 시각, 페이지 주소, 기기·브라우저, 재현 순서를 적어주세요. 선수 정보 문의에는 이름과 명단 기준일을 포함해주세요. 비밀번호나 민감한 개인정보는 보내지 마세요.</p>`],
    privacy: ['개인정보 안내', '게임을 이용할 때 전달되는 정보', `
      <p class="lead">이 페이지는 누크야!의 현재 웹 기능에서 사용하는 정보와 이용자가 선택할 수 있는 설정을 설명합니다. 개인정보 관련 문의는 <a href="mailto:fortelior@tendom.co.kr">fortelior@tendom.co.kr</a>로 보내주세요.</p><h2>게임 기능</h2><p>웹 게임에는 회원가입 입력란이 없습니다. 게임 진행을 위해 선택한 구단·모드·스태프 포함 여부, 검색한 선수명, 선택한 선수 식별자가 게임 API로 전달됩니다. 서버에서 발급한 게임 식별자는 게임 페이지 주소에 포함됩니다. 게임 주소를 다른 사람에게 공유할 때에는 해당 식별자도 함께 전달됩니다.</p><h2>브라우저에 저장하는 언어 설정</h2><p>선택한 언어는 브라우저의 로컬 저장소에 <code>nukya-language</code>라는 이름으로 저장됩니다. 이 값에는 언어 코드가 들어가며, 다음 방문 때 언어 선택에 사용됩니다. 브라우저 설정에서 이 사이트의 데이터를 삭제하면 지울 수 있습니다.</p><h2>이용 통계</h2><p>사이트에는 Google Analytics 연동이 포함되어 있습니다. 활성화된 경우 Google은 쿠키 등의 기술을 통해 페이지 이용, 기기·브라우저 등 이용 정보를 처리할 수 있습니다. 자세한 처리 방식은 <a href="https://policies.google.com/technologies/partner-sites?hl=ko">Google 파트너 사이트 정보 사용 안내</a>에서 확인할 수 있습니다. 브라우저의 쿠키 설정과 <a href="https://tools.google.com/dlpage/gaoptout?hl=ko">Google Analytics 차단 도구</a>를 통해 수집을 제어할 수 있습니다.</p><h2>광고 및 외부 서비스</h2><p>Google 광고가 활성화된 게임 화면에서는 Google 광고 스크립트가 로드될 수 있습니다. Google을 포함한 광고 제공자는 쿠키를 사용하여 이전 사이트 방문을 바탕으로 광고를 제공할 수 있습니다. <a href="https://myadcenter.google.com/">Google 광고 설정</a>에서 개인 맞춤 광고를 관리할 수 있습니다. 자체 홍보 배너 링크에는 유입 경로와 선택한 구단을 나타내는 값이 포함될 수 있습니다. 배너를 누르면 외부 사이트의 정책이 적용됩니다. 글꼴 제공을 위해 Google Fonts에 연결합니다.</p><h2>이메일 문의와 개인정보 요청</h2><p>문의 메일을 보내면 발신 이메일 주소와 본문·첨부 내용이 문의 수신자에게 전달됩니다. 필요한 정보만 보내주세요. 자신이 보낸 문의의 열람·정정·삭제 등 개인정보 관련 요청은 같은 연락처로 보내실 수 있습니다. 서버 로그, 게임 기록, 분석 데이터와 문의 메일의 실제 보관 기간 및 삭제 처리에 관한 세부 사항은 운영팀에 문의해주세요.</p><p class="note">안내 기준일: 2026년 9월 17일. 기능이나 정보 사용 방식이 바뀌면 이 안내를 갱신합니다.</p>`],
  },
  en: {
    about: ['About & contact', 'About Nu-Kya!', `
      <p class="lead">Nu-Kya! is a free Korean baseball guessing game. It is about combining clues as well as remembering names: each guess tells you something about a hidden player.</p><h2>The game</h2><p>Find a player within nine guesses by comparing team, position, jersey number, throwing hand, batting side, birth year, height and weight. Choose a familiar team or several teams, and expand the pool to Futures players or staff. Korean and English interfaces are available.</p><h2>Reference data</h2><p>Use the roster date shown in the game as your reference. Transfers, registrations and profile corrections may not be reflected immediately. Check the <a href="https://www.koreabaseball.com/">official KBO website</a> when you need the latest official information. A game result is not an official player record.</p><h2>Advertising and links</h2><p>Promotional banners may link to external services and are identified as advertisements. Google ads, when enabled, are not requested on setup, error or information pages. External services have their own terms and privacy practices.</p><h2>Contact</h2><p><a class="button" href="mailto:fortelior@tendom.co.kr">fortelior@tendom.co.kr</a></p><p>Contact us about corrections, technical issues, the service or privacy. For bugs, include the time, page URL, device, browser and steps to reproduce. For player corrections, include the player name and roster date. Please do not send passwords or sensitive personal information.</p>`],
    privacy: ['Privacy information', 'Information used by the game', `
      <p class="lead">This page describes information used by the current Nu-Kya! web features and the controls available to you. Contact <a href="mailto:fortelior@tendom.co.kr">fortelior@tendom.co.kr</a> for privacy questions.</p><h2>Game requests</h2><p>The web game does not have a registration form. Your chosen teams, mode, staff setting, player searches and guessed player identifiers are sent to the game API. A server-issued game identifier appears in the game URL and is included when you share that URL.</p><h2>Language preference</h2><p>The browser stores your chosen language locally under <code>nukya-language</code>. It contains a language code used on future visits. You can remove it by clearing this site’s data in your browser.</p><h2>Analytics</h2><p>The site includes a Google Analytics integration. When enabled, Google may use cookies and similar technologies to process page usage and device or browser information. See <a href="https://policies.google.com/technologies/partner-sites?hl=en">Google’s partner-site data information</a>. Browser cookie settings and the <a href="https://tools.google.com/dlpage/gaoptout?hl=en">Analytics opt-out tool</a> provide controls.</p><h2>Ads and external services</h2><p>When Google ads are enabled in the game, Google advertising scripts may load. Advertising providers, including Google, may use cookies to serve ads based on earlier visits. Manage Google ad personalization in <a href="https://myadcenter.google.com/">My Ad Center</a>. Promotional links may include referral and selected-team parameters. Linked websites apply their own privacy practices. Fonts are loaded from Google Fonts.</p><h2>Email and privacy requests</h2><p>Sending email discloses your sender address, message and attachments to the recipient. Send only what is needed. Use the same address to request access, correction or deletion of information you have provided. Contact the service team for operational details about retention and deletion of server logs, game records, analytics and email.</p><p class="note">Information date: September 17, 2026. This information is updated when features or information use change.</p>`],
  },
}

const css = `:root{font-family:system-ui,-apple-system,sans-serif;color:#18243b;background:#f7f9fc;line-height:1.85}*{box-sizing:border-box}body{margin:0}header,main,footer{max-width:820px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;gap:16px;border-bottom:1px solid #d8e0ed}a{color:#3157a2;text-underline-offset:4px}header a{text-decoration:none;font-weight:700}main{padding-top:52px;padding-bottom:56px}h1{font-size:clamp(30px,5vw,46px);line-height:1.25;letter-spacing:-.045em;margin:12px 0 24px}h2{margin-top:40px;font-size:23px;letter-spacing:-.025em}h3{margin-top:28px;font-size:18px}.eyebrow{font-size:12px;letter-spacing:.12em;color:#536b96}.lead{font-size:19px;color:#475569}.table-wrap{overflow-x:auto;margin:24px 0}table{border-collapse:collapse;width:100%;min-width:470px;background:#fff;font-size:14px}th,td{padding:14px;border:1px solid #d8e0ed;text-align:left}caption{text-align:left;padding-bottom:10px;color:#536174}thead{background:#edf2fa}.button{display:inline-block;padding:10px 18px;background:#e9effa;border-radius:8px;overflow-wrap:anywhere}.note{font-size:14px;color:#5d6b80;border-top:1px solid #d8e0ed;padding-top:20px}footer{border-top:1px solid #d8e0ed;font-size:14px}nav{display:flex;flex-wrap:wrap;gap:12px 24px}li{margin:10px 0}:focus-visible{outline:3px solid #678ad7;outline-offset:5px}@media(max-width:500px){header,main,footer{padding-left:20px;padding-right:20px}main{padding-top:30px}.lead{font-size:17px}}`
mkdirSync('public/content', {recursive:true})
writeFileSync('public/content/info.css', css)
for (const [lang, entries] of Object.entries(pages)) {
  const prefix = lang === 'en' ? '/en' : ''
  const home = lang === 'en' ? '/en/' : '/'
  for (const [slug, [title, heading, body]] of Object.entries(entries)) {
    const path = `${prefix}/${slug}/`
    const alternate = `${lang === 'en' ? '' : '/en'}/${slug}/`
    const nav = Object.entries(entries).map(([key,[label]])=>`<a href="${prefix}/${key}/"${key === slug ? ' aria-current="page"' : ''}>${label}</a>`).join('')
    const html = `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | ${lang === 'en' ? 'Nu-Kya!' : '누크야!'}</title><meta name="description" content="${heading}. ${title}"><link rel="canonical" href="https://nu-kya.com${path}"><link rel="alternate" hreflang="ko" href="https://nu-kya.com/${slug}/"><link rel="alternate" hreflang="en" href="https://nu-kya.com/en/${slug}/"><link rel="alternate" hreflang="x-default" href="https://nu-kya.com/${slug}/"><link rel="icon" href="/nukeya-mark.png"><link rel="stylesheet" href="/content/info.css"></head><body><header><a href="${home}">${lang === 'en' ? '← Nu-Kya! · Play' : '← 누크야! · 게임하기'}</a><a href="${alternate}" lang="${lang === 'en' ? 'ko' : 'en'}">${lang === 'en' ? '한국어' : 'English'}</a></header><main><p class="eyebrow">NU-KYA! / ${slug.toUpperCase()}</p><h1>${heading}</h1>${body}</main><footer><nav aria-label="${lang === 'en' ? 'Site information' : '사이트 안내'}">${nav}</nav><p><a href="${home}">${lang === 'en' ? 'Choose your teams and play →' : '구단을 고르고 게임 시작하기 →'}</a></p></footer></body></html>`
    mkdirSync(`public${path}`, {recursive:true})
    writeFileSync(`public${path}index.html`, html)
  }
}
